### ISSUE TITLE
BuildGen:setLocName(): is not localising entities

### ISSUE THREAD

**Issue by Cereal-Sam** [Omnimods/Omnimods#112]
The setLocName(): function of BuildGen is only setting the given localised name for the item and recipe, but not for the entity.

**Comment by Cereal-Sam** [comment]
Additional context:

The issue here seems to be that we only have 1 function and variable to set the localised name to.
When calling buildgen:import, first buildgen is called  with setLocName(), then recgen with setLocName and after that itemgen:setLocName().
If the Recipe or Item have a localised name, the entity one gets overwritten in this case.

At the same time its currently not possible to set different localised names via gen functions for a recipe /entity (/item).

To fix this, we definetly need a different internal variable for each (or a table) to store their localised name.
setLocName() needs to have  an argument to specify which one to change.

**Comment by Pezzawinkle** [comment]
I do agree that entities require localisation in preference to the item (allowing carry-through).
Recipes are generally set by main-product if that is set, otherwise we should be able to set a "default" if a value is not parsed.
