### ISSUE TITLE
[BUG] Omnifluid in Py (portal version)

### ISSUE THREAD

**Issue by tkozyrski** [Omnimods/Omnimods#397]
There's no way to get a Solid Korlex Milk which is an ingredient in a Good Alien Sample. It prevents game progress. Originally you get Filled Milk Barrel (using a custom canister) which you can empty to get Korlex Milk (fluid).

**Comment by Cereal-Sam** [comment]
Thank you for the repot.
This is due to PY not using standard naming schemes for barrels in the current portal version which results in this recipe not being caught automatically.
I already PRed a fix to py for his next release. Added a temp fix for the next fluid release too
