### ISSUE TITLE
[BUG] Omnifluid in Py (modportal version)

### ISSUE THREAD

**Issue by tkozyrski** [Omnimods/Omnimods#398]
There are multiple problems with coke oven gas recipes. As a product of different recipes you get coke oven gas with diffrerent temperatures. Omnifluid handles this well, however originally you can use different temperatures in a recipe , for example requirement can be Coke Oven Gas <250C. This is a spot when mod fails - with first oven recipe you get Coke Oven Gas 100C which you are unable to use, dispose or whatever.

**Comment by Cereal-Sam** [comment]
Thanks for bringing that up aswell, i added the coke gas recipes as exception so copies for each temperature exist
