### ISSUE TITLE
Compressed-science-pack-gold does not exist

### ISSUE THREAD

**Issue by infantryman4life** [Omnimods/Omnimods#404]
**Describe the bug**
Trying to load  SeaBlock with omni compression and it just errors after it was done loading the mods.

**To Reproduce**
loading all SeaBlock mods and omni lib and omni compression

**Expected behavior**
it shuts down

**Screenshots**
![ee](https://user-images.githubusercontent.com/60069986/178128178-0a540102-8d29-4543-9058-626805c5fff8.png)

**Additional context**
no

**Additional Info**
- Factorio Version: 1.1.61
- Minimal required mods to reproduce: SeaBlock mods and omni compression with lib
- Savegame:

**Comment by Pezzawinkle** [comment]
[factorio-current.log](https://github.com/Omnimods/Omnimods/files/9127841/factorio-current.log)
log for the above error:
Appears to be a "generic crash" needs a bit of digging into, but may be an issue with a tech duplication...

**Comment by infantryman4life** [comment]
sorry to not include the log
