### ISSUE TITLE
making omnide solution's/molten omnicium (metal) alloy compatible with compressed fluids mod

### ISSUE THREAD

**Issue by darkcamo12** [Omnimods/Omnimods#405]
playing a mod pack that is based around consuming lot of resources and would be really helpful if both omnide solution's and molten omnicium (metal) alloy's were able to be compressed using pressurized fluids ( https://mods.factorio.com/mod/CompressedFluids )

**Comment by Cereal-Sam** [comment]
Hi,
this seems like something that needs to be done on the side of CompressedFluids.
Could be just a load order issue.

**Comment by Cereal-Sam** [comment]
Omnide solutions have barreling recipes now and should work with CompressedFluids.
Thanks for the report
