### ISSUE TITLE
[BUG]Omnipermute incompatible with PyAL T.U.R.D.

### ISSUE THREAD

**Issue by 04Slash** [Omnimods/Omnimods#419]
**Describe the bug**
Clicking on the T.U.R.D. section of the Pyanodon Codex will cause a crash due to missing recipes. All other Pyanodon Codex pages have no issues.

**To Reproduce**
1. Download PyAL v2.1.0 or above
2. Use patched Omnipermute -> #417 
3. Ensure Factorio version 1.1.78 (Experimental) is being used for compatibility with PyCoalProcessing 2.0.8+ (PyAL dependency)
4. Load game, create world
5. Open Pyanodon Codex (top left) and click T.U.R.D.
6. Receive error and get kicked to main menu

**Expected behavior**
Clicking the T.U.R.D. section should result in no errors, and all available T.U.R.D. upgrades should be present (they're likely missing due to failing to load on Bhoddos-3).

**Screenshots**
![image](https://user-images.githubusercontent.com/57328541/228448110-e379cdd5-26e6-4a68-a790-3c8c76f35016.png)

**Additional context**
PyAlternativeEnergy and PyBlock were also used but are not required to replicate. The naptha-arqad recipe will be missing instead.

**Additional Info**
- Factorio Version: 1.1.78
- Minimal required mods to reproduce: Omnipermute + PyAL (+ Dependencies of both mods)
- Savegame: N/A

**Comment by Cereal-Sam** [comment]
This is a script error on PYs side not checking if recipes exist.

**Comment by 04Slash** [comment]
My apologies, I originally replicated this with PyAE present and the issue happened only when Omnipermute was added, and went away when Omnipermute was removed. I guess I never tried without PyAE present because a similar issue happens with just PyAL, no Omnipermute or PyAE. I will open a report in PyAL.

**Comment by Cereal-Sam** [comment]
No, problem.
It is basically triggered by omnipermute due to it´s renaming existing recipes to easily swap between the different recipe "versions" (with switched fluid orders).
Py scripts seem to do stuff for the hardcoded original recipe name without checking if the recipe exists
