### ISSUE TITLE
Support for Industrial Revolution 3

### ISSUE THREAD

**Issue by GamBar1709** [Omnimods/Omnimods#425]
I'm very frusrated bacuse Omnimods don't work with Industrial Revolution 3

Mod author (OmnissiahZelos) should make his mod compatible with IR3.

I tried to make this work myself but no success here.

**Additional Info:**
- Factorio Version 1.1.87

**Modlist:**
- Industrial Revolution 3 by Deadlock989
- Omnilibrary by OmnissiahZelos
- Omnimatter by OmnissiahZelos

**Comment by Cereal-Sam** [comment]
As explained multiple times on Discord:
This is not in our hand
