### ISSUE TITLE
[BUG] Omnilib's 'clone_function' crashes Omnilib on version 1.1.101 experimental

### ISSUE THREAD

**Issue by TommyC81** [Omnimods/Omnimods#429]
**Describe the bug**
Error when loading the mod with v1.1.101 (latest v1.1.x experimental).

**To Reproduce**
1. Start Factorio v1.1.101 (latest v1.1.x experimental)
2. Whilst latest Omnicompression mod installed only (v4.1.27) - Note: With its dependency Omnilibrary v4.1.39
3. Mod loading failure.
4. See error image below.

**Expected behavior**
Mod loads as expected.

**Screenshots**
![image](https://github.com/Omnimods/Omnimods/assets/1904092/7efe65e3-a041-4846-878a-82ba3c543856)

**Additional context**

**Additional Info**
- Factorio Version: v1.1.101 (latest v1.1.x experimental)
- Minimal required mods to reproduce: Omnicompression v4.1.27 (only loaded mod along with its dependency Omnilibrary v4.1.39)
- Savegame: N/A

**Comment by SqFKYo** [comment]
![image](https://github.com/Omnimods/Omnimods/assets/26864304/d9417176-ca87-497d-8205-110ccf800682)
The issue seems to be in the omnilib, no omnicompression is needed.

**Comment by SqFKYo** [comment]
101 seems to break the function cloning function that uses string.dump / load combo, as the load function returns nil instead of the cloned function. Need to investigate more if this is some side effect or a bug in Factorio itself.

**Comment by Cereal-Sam** [comment]
Thanks for the report, we have to wait now what the Factorio devs answer regarding this issue:
https://forums.factorio.com/viewtopic.php?f=7&t=110409
