### ISSUE TITLE
[BUG][Omnicompression] Cannot load when setting "omnicompression_1x1_buildings" equal to true

### ISSUE THREAD

**Issue by RedRafe** [Omnimods/Omnimods#447]
**Describe the bug**
When setting "omnicompression_1x1_buildings" to true (reducing compressors to 1x1 size) the game fails to load.

**Log**
```
   0.972 Error ModManager.cpp:1741: Error while loading entity prototype "auto-concentrator" (furnace): 
   Key "direction" not found in property tree at ROOT.furnace.auto-concentrator.fluid_boxes[0].pipe_connections[0]
Modifications: Omnicompression › Omnifluid
```
I'm on latest version of mods released on portal:
4.2.0 Omnicompression
4.2.0 Omnicrystal
3.2.0 Omnienergy
4.2.0 Omnifluid
4.2.0 Omnilib
4.2.0 Omnimatter
disabled Omnimover
4.2.0 Omniwater
4.2.0 Omniwood

**Comment by Cereal-Sam** [comment]
Thanks for the report, fixed version is out.
