### ISSUE TITLE
[BUG] Omnifluid + Full PY

### ISSUE THREAD

**Issue by tkozyrski** [Omnimods/Omnimods#449]
![image](https://github.com/user-attachments/assets/0666b8b2-bba4-4e16-a8ca-2ab0901e1820)

**Comment by tkozyrski** [comment]
After fix:

![image](https://github.com/user-attachments/assets/b43e1301-bc28-4ed7-ac2c-33173b1a7bc1)

**Comment by Cereal-Sam** [comment]
> After fix:
> 
> ![image](https://private-user-images.githubusercontent.com/15027727/391156772-b43e1301-bc28-4ed7-ac2c-33173b1a7bc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTk0MjIsIm5iZiI6MTczMzE1OTEyMiwicGF0aCI6Ii8xNTAyNzcyNy8zOTExNTY3NzItYjQzZTEzMDEtYmMyOC00ZWQ3LWFjMmMtMzMxNzNiMWE3YmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE3MDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZDFmYmI4MmJhZDI4ODdiMjAzZWYxMzA4NmQxMjUxZGUyYjQwMWM0N2MzYTdjYmVlZTVmM2YzNjc3Yjc0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xf1bPLBlAkkWScn7GrVYuhyQjXT8fddcS5PWaO2TBfU)

That's fixed with the commit afterwards
7d65eb74674627edd7ff0e94a666e8670cae6a72

**Comment by tkozyrski** [comment]
After last fix, again:
![image](https://github.com/user-attachments/assets/c9c01040-fc23-43a3-8fe2-13246eadfa44)
